### GET all packages
GET http://localhost:3000/api/package
Accept: application/json

### GET a package
GET http://localhost:3000/api/package/661534e2d7d42824d5868371
Accept: application/json

### Create package
POST http://localhost:3000/api/package
Content-Type: application/json

{
  "description": "desc 1",
  "active_delivery_id": "661534d1d7d42824d586836f",
  "weight": 10,
  "width": 10,
  "height": 5,
  "depth": 3,
  "from_name": "Senegal",
  "from_address": "Dakar,Senegal",
  "from_location": {"lat": 14.716677, "lng": -17.467686},
  "to_name": "Benin",
  "to_address": "Cotonou,Benin",
  "to_location": {"lat": 6.524379, "lng": 2.439228}
}

### Update package
PUT http://localhost:3000/api/package/14
Content-Type: application/json

{
  "from_address": "Thies,Senegal",
  "to_location": {"lat": 8.524379, "lng": -8.439228}
}

### Delete package
DELETE http://localhost:3000/api/package/11
Content-Type: application/json


#################### Delivery ####################



### GET all deliveries
GET http://localhost:3000/api/delivery
Accept: application/json

### GET a delivery
GET http://localhost:3000/api/delivery/661534cbd7d42824d586836d
Accept: application/json

### Create delivery
POST http://localhost:3000/api/delivery
Content-Type: application/json

{
  "package_id": "661534b2d7d42824d586836b",
  "description": "desc 1",
  "pickup_time": "2024-04-06",
  "start_time": "2024-04-06",
  "end_time": "2024-05-06",
  "location": {"lat": 14.716677, "lng": -17.467686},
  "status": "picked-up"
}

### Update delivery
PUT http://localhost:3000/api/delivery/661534d1d7d42824d586836f
Content-Type: application/json

{
  "status": "open",
  "start_time": "2020-04-06",
  "end_time": "2020-05-06"
}

### Delete delivery
DELETE http://localhost:3000/api/delivery/66152bd1c9c585061147b2d2
Content-Type: application/json
