version: '3'
services:
    app:
        build: .
        container_name: package_tracking_app
        volumes:
            - .:/app
        ports:
            - "3000:3000"
        environment:
            - MONGO_URI=mongodb://mongo:27017/package-tracking-db
        depends_on:
            - mongo
    mongo:
        image: mongo:latest
        container_name: mongo_db
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
#    frontend:
#        build: ./frontend
#        container_name: package_tracking_frontend
#        volumes:
#            - ./frontend:/angular
#        ports:
#            - "4200:4200"
volumes:
    mongo_data:
